In [2]:
import numpy as np
#np.array()

In [25]:
X= np.array([[1,1], [2,2],[3,3],[4,4],[5,5]]).T
np.cov(X)

array([[2.5, 2.5],
       [2.5, 2.5]])

In [26]:
X.shape

(2, 5)

In [29]:
np.dot(np.ones((2,5)),X.T)*1/5

array([[3., 3.],
       [3., 3.]])

In [33]:
X_differences = X-np.ones((2,5))*3
X_differences

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [34]:
np.dot(X_differences, X_differences.T)

array([[10., 10.],
       [10., 10.]])

In [ ]:
Its a singular matrix 

In [35]:
import numpy as np

def rotate(p, origin=(0, 0), degrees=0):
    angle = np.deg2rad(degrees)
    R = np.array([[np.cos(angle), -np.sin(angle)],
                  [np.sin(angle),  np.cos(angle)]])
    o = np.atleast_2d(origin)
    p = np.atleast_2d(p)
    return np.squeeze((R @ (p.T-o.T) + o.T).T)


points=[(200, 300), (100, 300)]
origin=(100,100)

new_points = rotate(points, origin=origin, degrees=10)
print(new_points)

[[163.75113977 314.32636837]
 [ 65.27036447 296.9615506 ]]


In [36]:

points=[(1,1), (2,2), (3,3), (4,4), (5,5)]
origin=(0,0)

new_points = rotate(points, origin=origin, degrees=45)


In [37]:
new_points

array([[0.        , 1.41421356],
       [0.        , 2.82842712],
       [0.        , 4.24264069],
       [0.        , 5.65685425],
       [0.        , 7.07106781]])

In [41]:
A = np.cov(X.T , new_points)

In [39]:
X.shape , new_points.shape

((2, 5), (5, 2))

In [44]:
np.linalg.eig(A)

(array([0.00000000e+00, 5.50000000e+01, 4.42196049e-16, 1.50376610e-30,
        6.75503996e-16, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  1.        ],
        [-0.99086739, -0.13483997, -0.17156039,  0.25592091,  0.13576

In [ ]:
# Ans Q1 : Sigma will be singular & lambda is zero, as some values are zero ? 

In [45]:
#Q2 
X= np.array([[5,1], [5,2],[5,3],[5,4],[5,5]]).T
np.cov(X)

array([[0. , 0. ],
       [0. , 2.5]])

In [46]:
#Q2 
X= np.array([[5,1], [5,2],[5,3],[4,3], [5,4],[5,5]]).T
np.cov(X)

array([[0.16666667, 0.        ],
       [0.        , 2.        ]])

In [47]:
# q3 
#Q2 
X= np.array([[-2,2], [-3, 3],[-4,4],[-5,5], [-6,6]]).T
np.cov(X)

array([[ 2.5, -2.5],
       [-2.5,  2.5]])